### Personal stuff

export ZSH=$HOME/.oh-my-zsh
export PATH=$HOME/bin:/usr/local/bin:$PATH
ZSH_CUSTOM=$HOME/dotfiles/oh-my-zsh
ZSH_THEME="cobalt2"
plugins=(
  git
)
source $ZSH/oh-my-zsh.sh
export EDITOR='sublime'
# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Load personal configs
ZSH_DIR=$(dirname $(readlink ~/.zshrc))
. ${ZSH_DIR}/aliases.zsh
. ${ZSH_DIR}/../git/git-aliases.zsh
